







PV:pn-rmfosal = "1.0.0"
PR:pn-rmfosal = "r3"
PACKAGE_ARCH:pn-rmfosal = "${MIDDLEWARE_ARCH}"











PV:pn-qtwayland = "5.15.7"
PR:pn-qtwayland = "r1"
PACKAGE_ARCH:pn-qtwayland = "${MIDDLEWARE_ARCH}"







# All of these iarm-query-powerstate, iarm-set-powerstate, iarm-event-sender,
# key-simulator and mfr-utils use sys_mon_tools repo.





























PV:pn-firebolt-ripple = "${RIPPLE_RELEASE_VER}"
PR:pn-firebolt-ripple = "r1"
PACKAGE_ARCH:pn-firebolt-ripple = "${MIDDLEWARE_ARCH}"




PACKAGE_ARCH:pn-libflac = "${MIDDLEWARE_ARCH}"







PV:pn-sqlite3see = "1.0.0"
PR:pn-sqlite3see = "r0"
PACKAGE_ARCH:pn-sqlite3see = "${MIDDLEWARE_ARCH}"
















###










PV:pn-rdkwindowmanager = "1.8.0"
PR:pn-rdkwindowmanager = "r0"
PACKAGE_ARCH:pn-rdkwindowmanager = "${MIDDLEWARE_ARCH}"
























PACKAGE_ARCH:pn-packagegroup-youtube-widgets = "${MIDDLEWARE_ARCH}"

