# This inc file contains the package versions and revision details
# for RDK HALIF Header implementations.
# see [https://github.com/rdk-e/meta-rdk-halif-headers] for information on HALIF headers

#RDK HAL Implementations
#-------------------------------------------------------

PV_pn-media-utils-soc-realtek = "${PV_pn-media-utils-headers}"
PR_pn-media-utils-soc-realtek = "1.0.0-r0"
PACKAGE_ARCH_pn-media-utils-soc-realtek = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-media-utils-soc-realtek = "c0d66badd98f83ead8553c30c8e6a28f6aba5c09"


#-------------------------------------------------------
PV_pn-closedcaption-hal-realtek = "${PV_pn-closedcaption-hal-headers}"
PR_pn-closedcaption-hal-realtek = "1.0.0-r0"
PACKAGE_ARCH_pn-closedcaption-hal-realtek = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-closedcaption-hal-realtek = "871a279f43eb82d6d30d0bd8de68b48ce2cfb693"


#-------------------------------------------------------
PV_pn-hdmicec-hal-realtek = "${PV_pn-hdmicecheader}"
PR_pn-hdmicec-hal-realtek = "1.0.0-r0"
PACKAGE_ARCH_pn-hdmicec-hal-realtek = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-hdmicec-hal-realtek = "884604d697c36c112f6349d40349782eb4bc3273"

#-------------------------------------------------------
PV_pn-iarmmgrs-hal-realtek = "${PV_pn-iarmmgrs-hal-headers}"
PR_pn-iarmmgrs-hal-realtek = "1.0.0-r0"
PACKAGE_ARCH_pn-iarmmgrs-hal-realtek = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-iarmmgrs-hal-realtek = "cbd3783eb258636a607bf8568a98ca4a2b7e9098"

#-------------------------------------------------------
PV_pn-rdk-gstreamer-utils-platform = "${PV_pn-rdk-gstreamer-utils-headers}"
PR_pn-rdk-gstreamer-utils-platform = "r0"
PACKAGE_ARCH_pn-rdk-gstreamer-utils-platform = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rdk-gstreamer-utils-platform = "739cdb76168a8071ee96eb255a584afbb110f719"

#-------------------------------------------------------
PV_pn-devicesettings-hal-realtek = "${PV_pn-devicesettings-hal-headers}"
PR_pn-devicesettings-hal-realtek = "1.0.0-r0"
PACKAGE_ARCH_pn-devicesettings-hal-realtek = "${VENDOR_LAYER_EXTENSION}"
SRCREV_devicesettingssocrealtek_pn-devicesettings-hal-realtek = "00e9459fe1fd2b8b8291ded50454148726fea4a5"
SRCREV_devicesettingsskyxione_pn-devicesettings-hal-realtek = "76c6243d140b951e3e69aec7909512446578bae8"


