PV_pn-iarmmgrs-hal-realtek = "1.0.0"
PR_pn-iarmmgrs-hal-realtek = "r0"
PACKAGE_ARCH_pn-iarmmgrs-hal-realtek = "${VENDOR_LAYER_EXTENSION}"

PV_pn-testagentlib = "2.9.0"
PR_pn-testagentlib = "r0"
PACKAGE_ARCH_pn-testagentlib = "${VENDOR_LAYER_EXTENSION}"

PV_pn-emmc-read-util = "1.0.0"
PR_pn-emmc-read-util = "r0"
PACKAGE_ARCH_pn-emmc-read-util = "${VENDOR_LAYER_EXTENSION}"

PV_pn-otp-program = "2.2"
PR_pn-otp-program = "r0"
PACKAGE_ARCH_pn-otp-program = "${VENDOR_LAYER_EXTENSION}"

#gstreamer components

GST_VERSION = "1.18.5"
GST_REVISION = "r0"

PV_pn-gstreamer1.0 = "${GST_VERSION}"
PR_pn-gstreamer1.0 = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0 = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-omx = "1.10.4"
PR_pn-gstreamer1.0-omx = "r0"
PACKAGE_ARCH_pn-gstreamer1.0-omx = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-libav = "${GST_VERSION}"
PR_pn-gstreamer1.0-libav = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-libav = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-meta = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-meta = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-meta = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-meta = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-meta = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-meta = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-rtsp-server = "${GST_VERSION}"
PR_pn-gstreamer1.0-rtsp-server = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-rtsp-server = "${VENDOR_LAYER_EXTENSION}"


PV_pn-gstreamer1.0-plugins-base = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-meta = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-meta = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-meta = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-meta-base = "${GST_VERSION}"
PR_pn-gstreamer1.0-meta-base = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-meta-base = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-playback = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-playback = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-playback = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-wavparse = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-wavparse = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-wavparse = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-audiofx = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-audiofx = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-audiofx = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-isomp4 = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-isomp4 = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-isomp4 = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-audioparsers = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-audioparsers = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-audioparsers = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-soup = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-soup = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-soup = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-gio = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-gio = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-gio = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-videoconvert  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-videoconvert  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-videoconvert = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-videoscale  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-videoscale  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-videoscale = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-volume  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-volume  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-volume = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-typefindfunctions  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-typefindfunctions  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-typefindfunctions = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-autodetect  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-autodetect  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-autodetect = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-avi  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-avi  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-avi = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-deinterlace  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-deinterlace  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-deinterlace = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-interleave  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-interleave  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-interleave = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-dash  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-dash  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-dash = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-mpegtsdemux  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-mpegtsdemux  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-mpegtsdemux = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-smoothstreaming  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-smoothstreaming  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-smoothstreaming = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-videoparsersbad  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-videoparsersbad  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-videoparsersbad = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-opusparse  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-opusparse  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-opusparse = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-matroska  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-matroska  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-matroska = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-app  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-app  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-app = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-audioconvert  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-audioconvert  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-audioconvert = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-audioresample  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-audioresample  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-audioresample = "${VENDOR_LAYER_EXTENSION}"

PV_pn-rtk-audio-service = "1.0.0"
PR_pn-rtk-audio-service = "r0"
PACKAGE_ARCH_pn-rtk-audio-service = "${VENDOR_LAYER_EXTENSION}"

PV_pn-libdrm = "2.4.100"
PR_pn-libdrm = "r0"
PACKAGE_ARCH_pn-libdrm = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-simpleshell = "1.3.0"
PR_pn-westeros-simpleshell = "r0"
PACKAGE_ARCH_pn-westeros-simpleshell = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-simplebuffer = "1.3.0"
PR_pn-westeros-simplebuffer = "r0"
PACKAGE_ARCH_pn-westeros-simplebuffer = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-soc = "1.3.0"
PR_pn-westeros-soc = "r0"
PACKAGE_ARCH_pn-westeros-soc = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-sink = "1.0.0"
PR_pn-westeros-sink = "r0"
PACKAGE_ARCH_pn-westeros-sink = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros = "1.0.0"
PR_pn-westeros = "r0"
PACKAGE_ARCH_pn-westeros = "${VENDOR_LAYER_EXTENSION}"

PV_pn-essos = "1.0.0"
PR_pn-essos = "r0"
PACKAGE_ARCH_pn-essos = "${VENDOR_LAYER_EXTENSION}"

#oss components
PV_pn-cairo = "1.16.0"
PR_pn-cairo = "r0"
PACKAGE_ARCH_pn-cairo = "${VENDOR_LAYER_EXTENSION}"

PV_pn-libepoxy = "1.5.4"
PR_pn-libepoxy = "r0"
PACKAGE_ARCH_pn-libepoxy = "${VENDOR_LAYER_EXTENSION}"


PV_pn-python3-pygobject = "3.34.0"
PR_pn-python3-pygobject = "r0"
PACKAGE_ARCH_pn-python3-pygobject = "${VENDOR_LAYER_EXTENSION}"

PV_pn-pango = "1.44.7"
PR_pn-pango = "r0"
PACKAGE_ARCH_pn-pango = "${VENDOR_LAYER_EXTENSION}"

PV_pn-make-mod-scripts = "1.0"
PR_pn-make-mod-scripts = "r0"
PACKAGE_ARCH_pn-make-mod-scripts = "${VENDOR_LAYER_EXTENSION}"

PV_pn-librsvg = "2.40.21"
PR_pn-librsvg = "r0"
PACKAGE_ARCH_pn-librsvg = "${VENDOR_LAYER_EXTENSION}"

PV_pn-python3-pycairo = "1.19.0"
PR_pn-python3-pycairo = "r0"
PACKAGE_ARCH_pn-python3-pycairo = "${VENDOR_LAYER_EXTENSION}"

PV_pn-sky-fpbutton-driver = "2.8"
PR_pn-sky-fpbutton-driver = "r0"
PACKAGE_ARCH_pn-sky-fpbutton-driver = "${VENDOR_LAYER_EXTENSION}"

PV_pn-xsign = "4.0.1"
PR_pn-xsign = "r0"
PACKAGE_ARCH_pn-xsign = "${VENDOR_LAYER_EXTENSION}"

PV_pn-librdkmfrlib0 = "7.0"
PR_pn-librdkmfrlib0 = "r0"
PACKAGE_ARCH_pn-librdkmfrlib0 = "${VENDOR_LAYER_EXTENSION}"

PV_pn-wipe-disk-partitions = "1.0.0"
PR_pn-wipe-disk-partitions = "r0"
PACKAGE_ARCH_pn-wipe-disk-partitions = "${VENDOR_LAYER_EXTENSION}"

PV_pn-early-display = "1.0.0"
PR_pn-early-display = "r0"
PACKAGE_ARCH_pn-early-display = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-early-display = "6e404e9e0614091c840436b5c9e01dc9947f4445"

PV_pn-rtk-tee = "1.0.0"
PR_pn-rtk-tee = "r0"
PACKAGE_ARCH_pn-rtk-tee = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secauthn = "1.0.0"
PR_pn-secauthn = "r0"
PACKAGE_ARCH_pn-secauthn = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi3-rtk = "3.0.0"
PR_pn-secapi3-rtk = "r0"
PACKAGE_ARCH_pn-secapi3-rtk = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi2-adapter = "1.0.0"
PR_pn-secapi2-adapter = "r0"
PACKAGE_ARCH_pn-secapi2-adapter = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi-common-hw = "2.3.0"
PR_pn-secapi-common-hw = "r0"
PACKAGE_ARCH_pn-secapi-common-hw = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi-rtk = "2.1.0"
PR_pn-secapi-rtk = "r0"
PACKAGE_ARCH_pn-secapi-rtk = "${VENDOR_LAYER_EXTENSION}"

PV_pn-closedcaption-hal-realtek = "1.0.0"
PR_pn-closedcaption-hal-realtek = "r0"
PACKAGE_ARCH_pn-closedcaption-hal-realtek = "${VENDOR_LAYER_EXTENSION}"

PV_pn-dvrmgr-hal-realtek = "1.0.0"
PR_pn-dvrmgr-hal-realtek = "r0"
PACKAGE_ARCH_pn-dvrmgr-hal-realtek = "${VENDOR_LAYER_EXTENSION}"

PV_pn-media-utils-soc-realtek = "1.0.0"
PR_pn-media-utils-soc-realtek = "r0"
PACKAGE_ARCH_pn-media-utils-soc-realtek = "${VENDOR_LAYER_EXTENSION}"

PV_pn-hdmicec-hal-realtek = "1.0.0"
PR_pn-hdmicec-hal-realtek = "r0"
PACKAGE_ARCH_pn-hdmicec-hal-realtek = "${VENDOR_LAYER_EXTENSION}"

PV_pn-devicesettings-hal-realtek = "1.0.0"
PR_pn-devicesettings-hal-realtek = "r0"
PACKAGE_ARCH_pn-devicesettings-hal-realtek = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi-crypto-rtk = "2.3.0"
PR_pn-secapi-crypto-rtk = "r0"
PACKAGE_ARCH_pn-secapi-crypto-rtk = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi-common-crypto = "2.3.0"
PR_pn-secapi-common-crypto = "r0"
PACKAGE_ARCH_pn-secapi-common-crypto = "${VENDOR_LAYER_EXTENSION}"

PV_pn-testagent-loader = "2.3.0"
PR_pn-testagent-loader = "r0"
PACKAGE_ARCH_pn-testagent-loader = "${VENDOR_LAYER_EXTENSION}"

PV_pn-qca6390-mod-wifi = "1.0.0"
PR_pn-qca6390-mod-wifi = "r0"
PACKAGE_ARCH_pn-qca6390-mod-wifi = "${VENDOR_LAYER_EXTENSION}"

PV_pn-qca-hciattach = "1.0.0"
PR_pn-qca-hciattach = "r0"
PACKAGE_ARCH_pn-qca-hciattach = "${VENDOR_LAYER_EXTENSION}"

PV_pn-emmc-fw-update = "1.0.0"
PR_pn-emmc-fw-update = "r0"
PACKAGE_ARCH_pn-emmc-fw-update = "${VENDOR_LAYER_EXTENSION}"

PV_pn-mount-disk-partition = "1.0.0"
PR_pn-mount-disk-partition = "r0"
PACKAGE_ARCH_pn-mount-disk-partition = "${VENDOR_LAYER_EXTENSION}"

PV_pn-image-verifier-lib = "6.2.0"
PR_pn-image-verifier-lib = "r0"
PACKAGE_ARCH_pn-image-verifier-lib = "${VENDOR_LAYER_EXTENSION}"

PV_pn-flashapp = "5.9.2"
PR_pn-flashapp = "r0"
PACKAGE_ARCH_pn-flashapp = "${VENDOR_LAYER_EXTENSION}"

PV_pn-sky-led-driver = "1.0.0"
PR_pn-sky-led-driver = "r0"
PACKAGE_ARCH_pn-sky-led-driver = "${VENDOR_LAYER_EXTENSION}"

PV_pn-fmtsasidlibs = "2.4"
PR_pn-fmtsasidlibs = "r0"
PACKAGE_ARCH_pn-fmtsasidlibs = "${VENDOR_LAYER_EXTENSION}"

PV_pn-hank-mod-mali = "1.0.0"
PR_pn-hank-mod-mali = "r0"
PACKAGE_ARCH_pn-hank-mod-mali = "${VENDOR_LAYER_EXTENSION}"

PV_pn-rtkv1sink = "1.0.0"
PR_pn-rtkv1sink = "r0"
PACKAGE_ARCH_pn-rtkv1sink = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rtkv1sink = "0299d9662308bf99805fc3736f4e116eec7c1baf"

PV_pn-led-boot-pattern = "1.0.0"
PR_pn-led-boot-pattern = "r0"
PACKAGE_ARCH_pn-led-boot-pattern = "${VENDOR_LAYER_EXTENSION}"

PV_pn-rtkmali = "2.8.0"
PR_pn-rtkmali = "r0"
PACKAGE_ARCH_pn-rtkmali = "${VENDOR_LAYER_EXTENSION}"

PV_pn-platform-lib = "2.6.0"
PR_pn-platform-lib = "r0"
PACKAGE_ARCH_pn-platform-lib = "${VENDOR_LAYER_EXTENSION}"

PV_pn-rtk-audio-service = "1.0.0"
PR_pn-rtk-audio-service = "r0"
PACKAGE_ARCH_pn-rtk-audio-service = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rtk-audio-service = "6bb3a0f37357296c4f0697c1c4ecd9d69f45eb02"

PV_pn-hdmiservice = "1.0.0"
PR_pn-hdmiservice = "r0"
PACKAGE_ARCH_pn-hdmiservice = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-hdmiservice = "fa70b36fbeb22cd11179f49f74dda4a9360356c9"

PV_pn-rtkpcrclksink = "1.0.0"
PR_pn-rtkpcrclksink = "r0"
PACKAGE_ARCH_pn-rtkpcrclksink = "${VENDOR_LAYER_EXTENSION}"
