# This file will include the device specifc component versions and revisions
require conf/include/vendor_pkg_versions_halif_impl.inc

#----------------------------------------------------------------------------------------
PV_pn-rtk-platform-conf = "2.6.0"
PR_pn-rtk-platform-conf = "r0"
PACKAGE_ARCH_pn-rtk-platform-conf = "${VENDOR_LAYER_EXTENSION}"

PV_pn-testagentlib = "2.9.0"
PR_pn-testagentlib = "r0"
PACKAGE_ARCH_pn-testagentlib = "${VENDOR_LAYER_EXTENSION}"

PV_pn-emmc-read-util = "3.3.4"
PR_pn-emmc-read-util = "r0"
PACKAGE_ARCH_pn-emmc-read-util = "${VENDOR_LAYER_EXTENSION}"

PV_pn-otp-program = "2.2"
PR_pn-otp-program = "r1"
PACKAGE_ARCH_pn-otp-program = "${VENDOR_LAYER_EXTENSION}"

#----------------------------------------------------------------------------------------
#gstreamer components

GST_VERSION = "1.18.5"
GST_REVISION = "r2"

PV_pn-gstreamer1.0 = "${GST_VERSION}"
PR_pn-gstreamer1.0 = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0 = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-meta-base = "${GST_VERSION}"
PR_pn-gstreamer1.0-meta-base = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-meta-base = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-omx = "1.10.4"
PR_pn-gstreamer1.0-omx = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-omx = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-libav = "${GST_VERSION}"
PR_pn-gstreamer1.0-libav = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-libav = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-meta = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-meta = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-meta = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-meta = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-meta = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-meta = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-rtsp-server = "${GST_VERSION}"
PR_pn-gstreamer1.0-rtsp-server = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-rtsp-server = "${VENDOR_LAYER_EXTENSION}"


PV_pn-gstreamer1.0-plugins-base = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-meta = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-meta = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-meta = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-meta-base = "${GST_VERSION}"
PR_pn-gstreamer1.0-meta-base = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-meta-base = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-playback = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-playback = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-playback = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-wavparse = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-wavparse = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-wavparse = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-audiofx = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-audiofx = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-audiofx = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-isomp4 = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-isomp4 = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-isomp4 = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-audioparsers = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-audioparsers = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-audioparsers = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-soup = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-soup = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-soup = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-gio = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-gio = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-gio = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-videoconvert  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-videoconvert  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-videoconvert = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-videoscale  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-videoscale  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-videoscale = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-volume  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-volume  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-volume = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-typefindfunctions  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-typefindfunctions  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-typefindfunctions = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-autodetect  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-autodetect  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-autodetect = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-avi  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-avi  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-avi = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-deinterlace  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-deinterlace  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-deinterlace = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-interleave  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-interleave  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-interleave = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-dash  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-dash  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-dash = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-mpegtsdemux  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-mpegtsdemux  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-mpegtsdemux = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-smoothstreaming  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-smoothstreaming  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-smoothstreaming = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-videoparsersbad  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-videoparsersbad  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-videoparsersbad = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-opusparse  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-opusparse  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-opusparse = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-bad-dashdemux = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-bad-dashdemux = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-bad-dashdemux = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-good-matroska  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-good-matroska  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-good-matroska = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-app  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-app  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-app = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-audioconvert  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-audioconvert  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-audioconvert = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gstreamer1.0-plugins-base-audioresample  = "${GST_VERSION}"
PR_pn-gstreamer1.0-plugins-base-audioresample  = "${GST_REVISION}"
PACKAGE_ARCH_pn-gstreamer1.0-plugins-base-audioresample = "${VENDOR_LAYER_EXTENSION}"

PV_pn-rtk-audio-service = "2.0.0"
PR_pn-rtk-audio-service = "r0"
PACKAGE_ARCH_pn-rtk-audio-service = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rtk-audio-service = "e52aef88fc80d0e3b6166000e8553a7b7dc7fa7a"

PV_pn-libdrm = "2.4.100"
PR_pn-libdrm = "r0"
PACKAGE_ARCH_pn-libdrm = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-simpleshell = "1.3.0"
PR_pn-westeros-simpleshell = "r0"
PACKAGE_ARCH_pn-westeros-simpleshell = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-simplebuffer = "1.3.0"
PR_pn-westeros-simplebuffer = "r0"
PACKAGE_ARCH_pn-westeros-simplebuffer = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-soc = "1.3.0"
PR_pn-westeros-soc = "r1"
PACKAGE_ARCH_pn-westeros-soc = "${VENDOR_LAYER_EXTENSION}"

PV_pn-westeros-sink = "2.0.0"
PR_pn-westeros-sink = "r0"
PACKAGE_ARCH_pn-westeros-sink = "${VENDOR_LAYER_EXTENSION}"
SRCREV_realtek_pn-westeros-sink = "5724b0f7c96b432e18f11f7c71a70a750ec34da2"

PV_pn-westeros = "1.0.0"
PR_pn-westeros = "r0"
PACKAGE_ARCH_pn-westeros = "${VENDOR_LAYER_EXTENSION}"

PV_pn-essos = "1.0.0"
PR_pn-essos = "r0"
PACKAGE_ARCH_pn-essos = "${VENDOR_LAYER_EXTENSION}"

#----------------------------------------------------------------------------------------
#oss components
PV_pn-cairo = "1.16.0"
PR_pn-cairo = "r0"
PACKAGE_ARCH_pn-cairo = "${VENDOR_LAYER_EXTENSION}"

PV_pn-libepoxy = "1.5.4"
PR_pn-libepoxy = "r1"
PACKAGE_ARCH_pn-libepoxy = "${VENDOR_LAYER_EXTENSION}"

PV_pn-python3-pygobject = "3.34.0"
PR_pn-python3-pygobject = "r0"
PACKAGE_ARCH_pn-python3-pygobject = "${VENDOR_LAYER_EXTENSION}"

PV_pn-pango = "1.44.7"
PR_pn-pango = "r0"
PACKAGE_ARCH_pn-pango = "${VENDOR_LAYER_EXTENSION}"

PV_pn-make-mod-scripts = "1.0"
PR_pn-make-mod-scripts = "r0"
PACKAGE_ARCH_pn-make-mod-scripts = "${VENDOR_LAYER_EXTENSION}"

PV_pn-librsvg = "2.40.21"
PR_pn-librsvg = "r0"
PACKAGE_ARCH_pn-librsvg = "${VENDOR_LAYER_EXTENSION}"

PV_pn-python3-pycairo = "1.19.0"
PR_pn-python3-pycairo = "r0"
PACKAGE_ARCH_pn-python3-pycairo = "${VENDOR_LAYER_EXTENSION}"

#------------------------------------------------------------------------------------------
PV_pn-sky-fpbutton-driver = "2.8"
PR_pn-sky-fpbutton-driver = "r0"
PACKAGE_ARCH_pn-sky-fpbutton-driver = "${VENDOR_LAYER_EXTENSION}"

PV_pn-xsign = "4.0.1"
PR_pn-xsign = "r1"
PACKAGE_ARCH_pn-xsign = "${VENDOR_LAYER_EXTENSION}"

PV_pn-mfrlib-hal-xione = "7.0.4"
PR_pn-mfrlib-hal-xione = "r0"
PACKAGE_ARCH_pn-mfrlib-hal-xione = "${VENDOR_LAYER_EXTENSION}"

PV_pn-wipe-disk-partitions = "1.0.0"
PR_pn-wipe-disk-partitions = "r0"
PACKAGE_ARCH_pn-wipe-disk-partitions = "${VENDOR_LAYER_EXTENSION}"

PV_pn-early-display = "2.0.0"
PR_pn-early-display = "r0"
PACKAGE_ARCH_pn-early-display = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-early-display = "GRT_STB_v2"

PV_pn-rtk-tee = "1.0.0"
PR_pn-rtk-tee = "r0"
PACKAGE_ARCH_pn-rtk-tee = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secauthn = "1.0.0"
PR_pn-secauthn = "r0"
PACKAGE_ARCH_pn-secauthn = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi-rtk = "2.1.0"
PR_pn-secapi-rtk = "r1"
PACKAGE_ARCH_pn-secapi-rtk = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-secapi-rtk = "95b6bd4145b166b36febd6642d81b13c91a60e2a"

PV_pn-secapi3-rtk = "3.0.0"
PR_pn-secapi3-rtk = "r0"
PACKAGE_ARCH_pn-secapi3-rtk = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-secapi3-rtk = "aa3c293699853f5a4f54909124af9bb3f7ebf26b"

PV_pn-secapi2-adapter = "1.0.0"
PR_pn-secapi2-adapter = "r0"
PACKAGE_ARCH_pn-secapi2-adapter = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi-common-hw = "2.3.0"
PR_pn-secapi-common-hw = "r0"
PACKAGE_ARCH_pn-secapi-common-hw = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-secapi-common-hw = "3a51b8831ded9d28eed5150ba6d77508f7c3e1d2"

PV_pn-secapi-netflix = "1.0.0"
PR_pn-secapi-netflix = "r0"
SRCREV_com_inc_rtk_pn-secapi-netflix = "0fa3af310fb254d57e55cb79c52c14280b05997b"
SRCREV_socrealtek_pn-secapi-netflix = "d3c7c87f2d0cb1fdbd2b2536f0686d4b9f2367d3"
PACKAGE_ARCH_pn-secapi-netflix = "${VENDOR_LAYER_EXTENSION}"

PV_pn-systemaudioplatform = "1.0.0"
PR_pn-systemaudioplatform = "r0"
PACKAGE_ARCH_pn-systemaudioplatform = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-systemaudioplatform = "776348dfeab3b10a006ea170d1e21739dbd3e05a"

PV_pn-dvrmgr-hal-realtek = "1.0.0"
PR_pn-dvrmgr-hal-realtek = "r0"
PACKAGE_ARCH_pn-dvrmgr-hal-realtek = "${VENDOR_LAYER_EXTENSION}"

PV_pn-secapi-crypto-rtk = "2.3.0"
PR_pn-secapi-crypto-rtk = "r0"
PACKAGE_ARCH_pn-secapi-crypto-rtk = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-secapi-crypto-rtk = "f5eb9240383e67fb9aaf0a8d67791ca5ad2b91f7"

PV_pn-secapi-common-crypto = "2.3.0"
PR_pn-secapi-common-crypto = "r0"
PACKAGE_ARCH_pn-secapi-common-crypto = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-secapi-common-crypto = "3a51b8831ded9d28eed5150ba6d77508f7c3e1d2"

PV_pn-testagent-loader = "2.3.0"
PR_pn-testagent-loader = "r0"
PACKAGE_ARCH_pn-testagent-loader = "${VENDOR_LAYER_EXTENSION}"

PV_pn-qca6390-mod-wifi = "1.0.0"
PR_pn-qca6390-mod-wifi = "r0"
PACKAGE_ARCH_pn-qca6390-mod-wifi = "${VENDOR_LAYER_EXTENSION}"

PV_pn-qca-hciattach = "1.0.0"
PR_pn-qca-hciattach = "r0"
PACKAGE_ARCH_pn-qca-hciattach = "${VENDOR_LAYER_EXTENSION}"

PV_pn-emmc-fw-update = "1.0.0"
PR_pn-emmc-fw-update = "r0"
PACKAGE_ARCH_pn-emmc-fw-update = "${VENDOR_LAYER_EXTENSION}"

PV_pn-mount-disk-partition = "1.0.0"
PR_pn-mount-disk-partition = "r0"
PACKAGE_ARCH_pn-mount-disk-partition = "${VENDOR_LAYER_EXTENSION}"

PV_pn-image-verifier-lib = "6.2.0"
PR_pn-image-verifier-lib = "r0"
PACKAGE_ARCH_pn-image-verifier-lib = "${VENDOR_LAYER_EXTENSION}"

PV_pn-flashapp = "5.9.2"
PR_pn-flashapp = "r0"
PACKAGE_ARCH_pn-flashapp = "${VENDOR_LAYER_EXTENSION}"

PV_pn-sky-led-driver = "1.0.0"
PR_pn-sky-led-driver = "r0"
PACKAGE_ARCH_pn-sky-led-driver = "${VENDOR_LAYER_EXTENSION}"

PV_pn-fmtsasidlibs = "2.4"
PR_pn-fmtsasidlibs = "r0"
PACKAGE_ARCH_pn-fmtsasidlibs = "${VENDOR_LAYER_EXTENSION}"

PV_pn-hank-mod-mali = "1.0.0"
PR_pn-hank-mod-mali = "r1"
PACKAGE_ARCH_pn-hank-mod-mali = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-hank-mod-mali = "GRT_STB_v2"

PV_pn-rtkv1sink = "2.0.0"
PR_pn-rtkv1sink = "r0"
PACKAGE_ARCH_pn-rtkv1sink = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rtkv1sink = "GRT_STB_v2"

PV_pn-led-boot-pattern = "1.0.0"
PR_pn-led-boot-pattern = "r0"
PACKAGE_ARCH_pn-led-boot-pattern = "${VENDOR_LAYER_EXTENSION}"

PV_pn-rtkmali = "2.8.0"
PR_pn-rtkmali = "r0"
PACKAGE_ARCH_pn-rtkmali = "${VENDOR_LAYER_EXTENSION}"

PV_pn-platform-lib = "2.6.0"
PR_pn-platform-lib = "r2"
PACKAGE_ARCH_pn-platform-lib = "${VENDOR_LAYER_EXTENSION}"

PV_pn-rtk-audio-service = "2.0.0"
PR_pn-rtk-audio-service = "r0"
PACKAGE_ARCH_pn-rtk-audio-service = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rtk-audio-service = "6bb3a0f37357296c4f0697c1c4ecd9d69f45eb02"

PV_pn-hdmiservice = "2.0.0"
PR_pn-hdmiservice = "r0"
PACKAGE_ARCH_pn-hdmiservice = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-hdmiservice = "GRT_STB_v2"

PV_pn-rtkpcrclksink = "2.0.0"
PR_pn-rtkpcrclksink = "r0"
PACKAGE_ARCH_pn-rtkpcrclksink = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rtkpcrclksink= "GRT_STB_v2"

#-----------------------------------------------------------------------------

#Linux kernel components

PV_pn-linux-libc-headers = "4.9"
PR_pn-linux-libc-headers = "r4"
PACKAGE_ARCH_pn-linux-libc-headers = "${VENDOR_LAYER_EXTENSION}"

LINUX_HANK_PV = "4.9.119.01"
LINUX_HANK_PR = "r4"
PV_pn-packagegroup-kernel-modules = "${LINUX_HANK_PV}"
PR_pn-packagegroup-kernel-modules = "${LINUX_HANK_PR}"
PACKAGE_ARCH_pn-packagegroup-kernel-modules = "${VENDOR_LAYER_EXTENSION}"

PV_pn-linux-hank = "${LINUX_HANK_PV}"
PR_pn-linux-hank = "${LINUX_HANK_PR}"
PACKAGE_ARCH_pn-linux-hank = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-linux-hank = "e608d5faf955cd54a9cb8885d68f192c7e5644d9"

#-----------------------------------------------------------------------------

# MediaRite components
PV_pn-mediarite-vendor = "10.0.34.0a2"
PR_pn-mediarite-vendor = "r0"
PACKAGE_ARCH_pn-mediarite-vendor = "${VENDOR_LAYER_EXTENSION}"

PV_pn-gst-plugins-mediarite = "1.0"
PR_pn-gst-plugins-mediarite = "r0"
PACKAGE_ARCH_pn-gst-plugins-mediarite = "${VENDOR_LAYER_EXTENSION}"

#-----------------------------------------------------------------------------

PV_pn-rtkaudiosink = "2.0.0"
PR_pn-rtkaudiosink = "r0"
PACKAGE_ARCH_pn-rtkaudiosink = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-rtkaudiosink = "GRT_STB_v2"

PV_pn-sky-dropbear = "1.0.0"
PR_pn-sky-dropbear = "r0"
PACKAGE_ARCH_pn-sky-dropbear = "${VENDOR_LAYER_EXTENSION}"

PV_pn-mfi-ree = "2.0.0"
PR_pn-mfi-ree = "r0"
PACKAGE_ARCH_pn-mfi-ree = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-mfi-ree = "GRT_v2"

PV_pn-sysint-oem = "1.0.0"
PR_pn-sysint-oem = "r0"
PACKAGE_ARCH_pn-sysint-oem = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-sysint-oem = "ec0f597de266827521e9aa4d673c52e7f85118c0"

PV_pn-sysint-soc = "1.0.0"
PR_pn-sysint-soc = "r0"
PACKAGE_ARCH_pn-sysint-soc = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-sysint-soc = "c3ae6f44e6254045b50bc1ae3a9250e450496824"

PV_pn-apparmor-vendor = "1.0.0"
PR_pn-apparmor-vendor = "r0"
PACKAGE_ARCH_pn-apparmor-vendor = "${VENDOR_LAYER_EXTENSION}"
SRCREV_apparmor-profiles_pn-apparmor-vendor = "41e367427f7b647f17a7ad97571b024affae44dd"

PV_pn-directfb = "1.7.7"
PR_pn-directfb = "r0"
PACKAGE_ARCH_pn-directfb = "${VENDOR_LAYER_EXTENSION}"

PV_pn-audiocapturemgr-vendor = "1.0.0"
PR_pn-audiocapturemgr-vendor = "r0"
PACKAGE_ARCH_pn-audiocapturemgr-vendor = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-audiocapturemgr-vendor= "a063707e44eb91a3bd66b499b18f45cd5c41014d"

PV_pn-gst-svp-ext = "1.0.0"
PR_pn-gst-svp-ext = "r0"
PACKAGE_ARCH_pn-gst-svp-ext = "${VENDOR_LAYER_EXTENSION}"
SRCREV_gst_svp_ext = "2112843d24318e434f8605c1c741244e7623c5f4"
SRCREV_gst_svp_ext_device = "3b939f94fe7a3e0f62b202699f40a544a275784f"

PV_pn-realtek-collectd-plugins = "1.0.0"
PR_pn-realtek-collectd-plugins = "r0"
PACKAGE_ARCH_pn-realtek-collectd-plugins = "${VENDOR_LAYER_EXTENSION}"
SRCREV_pn-realtek-collectd-plugins = "032a4bede4be1556be53d86723c2d231b0bf88db"
