name: Unit tests

on:
  pull_request:
    branches: [ develop, main ]

env:
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME }}
  AUTOMATICS_PASSCODE: ${{ secrets.AUTOMATICS_PASSCODE }}
  WORKSPACE: ${{ github.workspace }}
  CI_CONTAINER: ${{ secrets.CI_CONTAINER }}
  TEST_RESULTS_SERVER: ${{ secrets.TEST_RESULTS_SERVER }}

jobs:
  execute-unit-tests-on-pr:
    name: Execute unit tests in gtest test suite
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_CONTAINER }}

    steps:
      - name: Checkout aamp code
        uses: actions/checkout@v3
        with:
            path: aamp

      - name: Run unit tests
        if: env.CI_CONTAINER != ''
        run: /bin/bash aamp/test/run_ut.sh

      - name: Upload test results to automatic test result management system
        if: env.CI_CONTAINER != ''
        run: >
          gtest-json-result-push.py /tmp/Gtest_Report ${{ env.TEST_RESULTS_SERVER }} `pwd`